#!/usr/local/bin/python3
import time
import socket
import os
import subprocess
import sys
import platform

def local_ip():
	try:
		s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
		s.connect(("8.8.8.8", 80))
		return s.getsockname()[0]
	except:
		return None



def host_name():
	try:
		return socket.gethostname()
	except:
		return None

def os_version():
	
	try:
		return platform.linux_distribution(distname='', version='', id='', supported_dists=('SuSE', 'debian', 'redhat', 'mandrake', ...), full_distribution_name=1)

	except:
		return None

def model():
	try:
		return None
	except:
		return None

def screen_size():
	try:
		return os.platform()

		
	except:
		return None

"""def uptime():
	try:
		os.system("uptime | grep 'Time since boot:' > .tmp.txt")

		with open(".tmp.txt", "r") as f:
			for info in f:
				return info.strip()[17:]
	except:
		return None"""


def uptime():
	try:
		return None
	except:
		return None

def shell():
	try:
		return os.environ.get('SHELL', '')
	except:
		return None

def kernel():
	try:
		return platform.release()
	except:
		return None

def cpu_spec():
	try:
		return platform.processor()
	except:
		return None

def battery_percentage():
	try:
		return None
	except:
		return None

def gpu_spec():
	pass

def memory():
	pass




"""def SSID():
	try:
		


	except:
		return None"""

TEMPLATE = """
                                     {hostname} 
                                            {hostname_sep}
                                                         OS: {os_version}
  MMMMMMMMMMMMMMMMMMMMMMMMMmds+.                         Kernel: {kernel}
MMm----::-://////////////oymNMd+`                        Model: {model}
MMd      /++                -sNMd:                       Shell: {shell}
MMNso/`  dMM    `.::-. .-::.` .hMN:                      Uptime: {uptime}
ddddMMh  dMM   :hNMNMNhNMNMNh: `NMm                      Resolution: {size}
    NMm  dMM  .NMN/-+MMM+-/NMN` dMM                      CPU: {cpu}
    NMm  dMM  -MMm  `MMM   dMM. dMM                      Local IP: {local_ip}
    NMm  dMM  -MMm  `MMM   dMM. dMM                      Battery: {battery_percentage}
    NMm  dMM  -MMm  'MMM'  dMM. dMN                      GPU: {gpu}                    
    NMm  dMM  .mmd  `mmm   yMM. dMM    			 Memory: {memory}
    NMm  dMM`  mmd   mmm   ydm. dMM   
    hMM- +MMd/-------...-:sdds  dMM   
    -NMm- :hNMNNNmdddddddddy/`  dMM   
     -dMNs-``-::::-------.``    dMM   
      `/dMNmy+/:-------------:/yMMM   
         ./ydNMMMMMMMMMMMMMMMMMMMMM  
            .MMMMMMMMMMMMMMMMMMM                                                         
                                                        
                                                         
                                                         
                                                         
                                                         
                                                        
                                                         
"""


print(TEMPLATE.format(hostname = host_name(),
	hostname_sep = "-" * len(host_name()),
	os_version=os_version(),
	kernel=kernel(),
	model=model(),
	shell=shell(),
	uptime=uptime(),
	size=screen_size(),
	cpu=cpu_spec(),
	local_ip=local_ip(),
	battery_percentage=battery_percentage(),
	gpu=gpu_spec(),
	memory = memory(),
)
)
os.system("rm -rf .tmp.txt")


